 name: trackpy-examples
 channels:
   - defaults
   - conda-forge
 dependencies:
   - python=3
   - pip
   - six
   - pyyaml
   - jinja2
   - scikit-image
   # Uncomment these if you need to analyze a movie file.
   #- ffmpeg
   #- av
   #- moviepy
   # Latest stable releases of trackpy and pims
   - trackpy
   - pims
   - numba
   - scipy
   - pytables
   - pandas
   - matplotlib
   - ipyparallel

